{{- if .Values.MySql_Secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: kubernetes.io/basic-auth
stringData:
  password: {{ .Values.MySql_Secret.password }}

#   secretGenerator:
# - name: mysql-pass
#   literals:
#   - password=YOUR_PASSWORD
{{- end }}